server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;

  resolver 127.0.0.11 valid=10s ipv6=off;
  set $core core:8002;
  set $supporting supporting:8001;

  location /api/depositors {
    proxy_pass http://$core$request_uri;
  }

  location /api/countries {
    proxy_pass http://$core$request_uri;
  }

  location /api/deposits {
    proxy_pass http://$core$request_uri;
  }

  location /api/currencies {
    proxy_pass http://$core$request_uri;
  }

  location /api/contracts {
    proxy_pass http://$core$request_uri;
  }

  location /api/reports {
    proxy_pass http://$core$request_uri;
  }

  location /api/plans {
    proxy_pass http://$core$request_uri;
  }

  location /api/portfolio {
    proxy_pass http://$core$request_uri;
  }

  location /api/ {
    proxy_pass http://$supporting$request_uri;
  }

  location = /about {
    try_files /pages/about/about.html =404;
  }

  location = /dashboard {
    try_files /pages/dashboard/dashboard.html =404;
  }

  location ~ "^/[a-zA-Z0-9_]+$" {
    try_files /pages/profile/profile.html =404;
  }

  location / {
    add_header Cache-Control "no-cache";
    try_files $uri $uri/ =404;

    error_page 404 = @error404;
    error_page 500 502 503 504 = @error500;
  }

  location @error404 { return 302 /pages/error/error.html?code=404; }
  location @error500 { return 302 /pages/error/error.html?code=500; }
}
