server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;

  location /api/ {
    proxy_pass http://supporting:8001;
  }

  location / {
    try_files $uri $uri/ =404;
  }

  error_page 404 = @error404;
  location @error404 { return 302 /pages/error.html?code=404; }

  error_page 500 502 503 504 = @error500;
  location @error500 { return 302 /pages/error.html?code=500; }
}
