const ENGLISH = "english";
const RUSSIAN = "russian";

const TRANSLATIONS = {
  "Home": "Главная",
  "Dashboard": "Панель",
  "Depositor": "Вкладчик",
  "Deposit": "Вклад",
  "Contract": "Договор",
  "Report": "Отчёт",
  "Return Plan": "План возврата",
  "Profile": "Профиль",
  "Support": "Поддержка",
  "English": "Русский",
  "DepositOne is an internal platform for the operational tracking of deposit agreements and the viewing of analytics.": "DepositOne – внутренняя платформа для оперативного учёта депозитных договоров и просмотра аналитики.",
  "© 2026 DepositOne. All rights reserved.": "© 2026 DepositOne. Все права защищены.",
  "Welcome Back": "С возвращением",
  "Returning": "Возвращение",
  "DepositOne is an internal platform for tracking deposit agreements and viewing analytics.": "DepositOne – внутренняя платформа для учёта депозитных договоров и просмотра аналитики.",
  "Get Started": "Начать работу",
  "Opportunities and services provided": "Возможности и предоставляемые услуги",
  "Registration of client cards, passport and contact details.": "Регистрация карточек клиентов, паспортных и контактных данных.",
  "Account opening, interest accrual, term monitoring.": "Открытие счетов, начисление процентов, контроль сроков.",
  "Generation, signing, and storage of depositor agreements.": "Формирование, подписание и хранение договоров вкладчиков.",
  "Consolidated analytics – portfolio structure and cash flow.": "Сводная аналитика – структура портфеля и денежные потоки.",
  "Operational and regulatory portfolio reports.": "Операционные и регуляторные отчёты по портфелю.",
  "Deposit repayment schedule and liquidity provisioning.": "График возврата вкладов и обеспечение ликвидности.",
  "Move To Depositor": "Перейти к вкладчикам",
  "Move To Deposit": "Перейти к вкладам",
  "Move To Contract": "Перейти к договорам",
  "Move To Dashboard": "Перейти к панели",
  "Move To Report": "Перейти к отчётам",
  "Move To Returning Plan": "Перейти к планам возврата",
  "View Depositor": "Открыть",
  "View Deposit": "Открыть",
  "View Contract": "Открыть",
  "View Dashboard": "Открыть",
  "View Report": "Открыть",
  "View Return Plan": "Открыть",
  "Ready to conveniently track deposit agreements and view analytics?": "Готовы удобно вести депозитные договоры и смотреть аналитику?",
  "Join thousands of professionals working with investment-related data.": "Присоединяйтесь к тысячам специалистов, работающих с инвестиционными данными.",
  "Login": "Вход",
  "LogIn": "Войти",
  "Registration": "Регистрация",
  "Forgot Password?": "Забыли пароль?",
  "Need Account?": "Нужен аккаунт?",
  "Already have account?": "Уже есть аккаунт?",
  "Reset Password": "Сброс пароля",
  "Return to Login": "Вернуться ко входу",
  "Set New Password": "Новый пароль",
  "Enter Email": "Введите почту",
  "Enter Nickname": "Введите никнейм",
  "Enter Password": "Введите пароль",
  "Confirm Password": "Подтвердите пароль",
  "Show password": "Показать пароль",
  "Hide password": "Скрыть пароль",
  "Login failed": "Не удалось войти",
  "Registration failed": "Не удалось зарегистрироваться",
  "Reset failed": "Не удалось сбросить пароль",
  "Passwords do not match": "Пароли не совпадают",
  "Please check the form": "Проверьте форму",
  "Operational analytics": "Операционная аналитика",
  "A unified dashboard for monitoring active deposits, portfolio structure, and cash flows.": "Единая панель для контроля активных вкладов, структуры портфеля и денежных потоков.",
  "Total number of depositors": "Общее количество вкладчиков",
  "Total number of deposits": "Общее количество вкладов",
  "Total number of active deposits": "Общее количество активных вкладов",
  "Total portfolio value": "Общая стоимость портфеля",
  "Total accrued interest": "Всего начислено процентов",
  "depositors": "вкладчики",
  "deposits": "вклады",
  "portfolio": "портфель",
  "Percents": "Проценты",
  "Deposits": "Вклады",
  "Amount": "Сумма",
  "Active": "Активный",
  "Pending": "В ожидании",
  "Closed": "Закрыт",
  "Blocked": "Заблокирован",
  "Active deposits": "Активные вклады",
  "Status": "Статус",
  "Currency": "Валюта",
  "List of Top depositors": "Список ведущих вкладчиков",
  "See all Depositors": "Все вкладчики",
  "No Information": "Нет данных",
  "N/A": "Нет данных",
  "Name": "Имя",
  "Email": "Почта",
  "Phone": "Телефон",
  "Deposit ID": "ID вклада",
  "Depositor Administration": "Управление вкладчиками",
  "Manage member records with powerful search and simplified data access.": "Управляйте карточками участников с удобным поиском и простым доступом к данным.",
  "List of Depositors": "Список вкладчиков",
  "Add Depositor": "Добавить вкладчика",
  "No Depositors Found": "Вкладчики не найдены",
  "Searching in list of depositors": "Поиск по списку вкладчиков",
  "Depositor Card": "Карточка вкладчика",
  "New Depositor Card": "Новая карточка вкладчика",
  "Personal Data": "Личные данные",
  "First name": "Имя",
  "Last name": "Фамилия",
  "Date of Birth": "Дата рождения",
  "Country": "Страна",
  "Passport": "Паспорт",
  "TIN": "ИНН",
  "Address": "Адрес",
  "Choose country": "Выберите страну",
  "Choose date": "Выберите дату",
  "Create Depositor": "Создать вкладчика",
  "Save Changes": "Сохранить изменения",
  "Cancel": "Отмена",
  "Delete": "Удалить",
  "Deletion is impossible": "Удаление невозможно",
  "There are active deposits assigned to the card. Close them before deleting.": "К карточке привязаны активные вклады. Закройте их перед удалением.",
  "Deletion is impossible while there are active deposits": "Удаление невозможно, пока есть активные вклады",
  "There are deposits assigned to the card. Delete them before deleting.": "К карточке привязаны вклады. Удалите их перед удалением карточки.",
  "Deletion is impossible while there are deposits": "Удаление невозможно, пока есть вклады",
  "There is a contract assigned to the deposit. Delete it before deleting.": "К вкладу привязан договор. Удалите его перед удалением вклада.",
  "Deletion is impossible while there is a contract": "Удаление невозможно, пока есть договор",
  "Enter first name": "Введите имя",
  "Enter last name": "Введите фамилию",
  "Enter passport": "Введите паспорт",
  "Enter tax id": "Введите ИНН",
  "Enter phone": "Введите телефон",
  "Enter email": "Введите почту",
  "Enter address": "Введите адрес",
  "Management of Deposit": "Управление вкладами",
  "View and manage your deposits with information monitoring.": "Просматривайте вклады и управляйте ими с контролем информации.",
  "List of Deposits": "Список вкладов",
  "Add Deposit": "Добавить вклад",
  "No Deposits Found": "Вклады не найдены",
  "Searching in list of deposits": "Поиск по списку вкладов",
  "Deposit Card": "Карточка вклада",
  "New Deposit": "Новый вклад",
  "Deposit Parameters": "Параметры вклада",
  "Interest rate": "Процентная ставка",
  "Start date": "Дата начала",
  "End date": "Дата окончания",
  "Choose depositor": "Выберите вкладчика",
  "Choose currency": "Выберите валюту",
  "Choose status": "Выберите статус",
  "Choose start date": "Выберите дату начала",
  "Choose end date": "Выберите дату окончания",
  "Create Deposit": "Создать вклад",
  "Enter amount": "Введите сумму",
  "Enter interest rate": "Введите процентную ставку",
  "Management of Contract": "Управление договорами",
  "View and manage your contracts with information monitoring.": "Просматривайте договоры и управляйте ими с контролем информации.",
  "List of Contracts": "Список договоров",
  "Add Contract": "Добавить договор",
  "No Contracts Found": "Договоры не найдены",
  "Searching in list of contracts": "Поиск по списку договоров",
  "Contract Card": "Карточка договора",
  "New Contract": "Новый договор",
  "Contract Parameters": "Параметры договора",
  "Contract Number": "Номер договора",
  "Date of the contract": "Дата договора",
  "Signing status": "Статус подписания",
  "Signing Status": "Статус подписания",
  "Description of the term": "Описание условий",
  "Special conditions": "Особые условия",
  "Choose deposit": "Выберите вклад",
  "Choose date of the contract": "Выберите дату договора",
  "Create Contract": "Создать договор",
  "Automatically generated prefix - year/month/Deposit ID": "Автоматически сформированный префикс – год/месяц/ID вклада",
  "Signed": "Подписан",
  "Rejected": "Отклонён",
  "Enter description of the term": "Введите описание условий",
  "Enter special conditions": "Введите особые условия",
  "# year/month/Deposit ID": "# год/месяц/ID вклада",
  "Financial reports": "Финансовые отчёты",
  "Real-time cash flow by day, month, year and five-year period, as well as information on depositors.": "Денежные потоки в реальном времени за день, месяц, год и пять лет, а также информация о вкладчиках.",
  "Key cash flow indicators": "Ключевые показатели денежного потока",
  "Opening Balance": "Остаток на начало",
  "Total Inflow": "Общий приток",
  "Expected Outflow": "Ожидаемый отток",
  "Net Liquidity": "Чистая ликвидность",
  "Today": "Сегодня",
  "Month": "Месяц",
  "Year": "Год",
  "5 Years": "5 лет",
  "List of Reports": "Список отчётов",
  "No Reports Found": "Отчёты не найдены",
  "Searching in list of reports": "Поиск по списку отчётов",
  "Repayment schedule": "График возврата",
  "An up-to-date payment schedule and detailed monthly payment plan, including interest and total payment calculations.": "Актуальный график платежей и подробный ежемесячный план выплат с расчётом процентов и итоговой суммы.",
  "Monthly Results": "Итоги месяца",
  "The total amount of all scheduled repayments on active deposits for the current month": "Общая сумма всех плановых возвратов по активным вкладам за текущий месяц",
  "Returns": "Возвраты",
  "Reserve": "Резерв",
  "Tomorrow": "Завтра",
  "This week": "На этой неделе",
  "Priority List": "Приоритетный список",
  "Priority": "Приоритет",
  "List of returning plan": "Список планов возврата",
  "No Returning Plans Found": "Планы возврата не найдены",
  "Searching in list of returning plan": "Поиск по списку планов возврата",
  "Refund calculation": "Расчёт возврата",
  "Principal amount": "Сумма вклада",
  "Term-end accruals": "Начисления на конец срока",
  "Accrued": "Начислено",
  "Accrued interest": "Начисленные проценты",
  "To be paid": "К выплате",
  "Accrual history": "История начислений",
  "Date": "Дата",
  "Capitalization": "Капитализация",
  "To Return": "К возврату",
  "By the amount of the deposit portfolio": "По сумме депозитного портфеля",
  "Including accruals": "С учётом начислений",
  "Term": "Срок",
  "Payout": "Выплата",
  "Opened": "Открыт",
  "Opening date": "Дата открытия",
  "Return date": "Дата возврата",
  "Deposit body at the end of the term": "Тело вклада на конец срока",
  "Total Payout": "Итоговая выплата",
  "Amount to be paid": "Сумма к выплате",
  "Rest API contour": "Контур Rest API",
  "All modules are accessible via the secure JWT API.": "Все модули доступны через защищённый JWT API.",
  "Rest API list": "Список Rest API",
  "Searching in api list": "Поиск по списку api",
  "All": "Все",
  "Public": "Открытый",
  "Auth": "Авторизация",
  "System": "Система",
  "Contracts": "Договоры",
  "Reports": "Отчёты",
  "Plans": "Планы",
  "Dictionaries": "Справочники",
  "Register": "Регистрация",
  "Reset Check": "Проверка сброса",
  "Reset Confirm": "Подтверждение сброса",
  "Api List": "Список API",
  "Profile Token": "Токен профиля",
  "Depositor List": "Список вкладчиков",
  "Depositor Create": "Создание вкладчика",
  "Depositor Options": "Вкладчики для форм",
  "Depositor Update": "Обновление вкладчика",
  "Depositor Delete": "Удаление вкладчика",
  "Deposit List": "Список вкладов",
  "Deposit Create": "Создание вклада",
  "Deposit Options": "Вклады для форм",
  "Deposit Stats": "Статистика вкладов",
  "Deposit Update": "Обновление вклада",
  "Deposit Delete": "Удаление вклада",
  "Contract List": "Список договоров",
  "Contract Create": "Создание договора",
  "Contract Update": "Обновление договора",
  "Contract Delete": "Удаление договора",
  "Report List": "Список отчётов",
  "Cash Flow": "Денежный поток",
  "Plan List": "Список планов возврата",
  "Plan Summary": "Сводка по планам",
  "Plan Card": "Карточка плана",
  "Country List": "Список стран",
  "Currency List": "Список валют",
  "Create a new user account": "Создание нового аккаунта",
  "Sign in and receive an access token": "Вход и получение токена доступа",
  "Check an account before a password reset": "Проверка аккаунта перед сбросом пароля",
  "Save a new password for an account": "Сохранение нового пароля аккаунта",
  "Return dashboard analytics data": "Возвращает данные аналитики панели",
  "Return the list of available endpoints": "Возвращает список доступных эндпоинтов",
  "Return the account card of the current user": "Возвращает карточку текущего пользователя",
  "Release a new access token for the current user": "Выпускает новый токен доступа",
  "Search, sort and page through depositors": "Поиск, сортировка и постраничный вывод вкладчиков",
  "Create a depositor card": "Создание карточки вкладчика",
  "Return depositors for select fields": "Возвращает вкладчиков для полей выбора",
  "Return one depositor card": "Возвращает одну карточку вкладчика",
  "Update a depositor card": "Обновление карточки вкладчика",
  "Delete a depositor without active deposits": "Удаление вкладчика без активных вкладов",
  "Search, sort and page through deposits": "Поиск, сортировка и постраничный вывод вкладов",
  "Open a new deposit for a depositor": "Открытие нового вклада для вкладчика",
  "Return deposits for contract forms": "Возвращает вклады для форм договоров",
  "Return deposit counts and amounts by status and currency": "Возвращает количество и суммы вкладов по статусам и валютам",
  "Return one deposit with the calculated term": "Возвращает вклад с рассчитанным сроком",
  "Update the parameters of a deposit": "Обновление параметров вклада",
  "Delete a deposit without a contract": "Удаление вклада без договора",
  "Search, sort and page through contracts": "Поиск, сортировка и постраничный вывод договоров",
  "Create a contract for a deposit": "Создание договора для вклада",
  "Return one contract with deposit data": "Возвращает договор с данными вклада",
  "Update the terms of a contract": "Обновление условий договора",
  "Delete a contract": "Удаление договора",
  "Return portfolio reports by depositor": "Возвращает отчёты по портфелю в разрезе вкладчиков",
  "Return inflow, outflow and net liquidity by period": "Возвращает приток, отток и чистую ликвидность по периодам",
  "Search and page through return plans": "Поиск и постраничный вывод планов возврата",
  "Return monthly results and the priority list": "Возвращает итоги месяца и приоритетный список",
  "Return the repayment plan of one deposit": "Возвращает план возврата одного вклада",
  "Return portfolio and contract totals": "Возвращает итоги по портфелю и договорам",
  "Return the list of countries for depositor forms": "Возвращает список стран для форм вкладчиков",
  "Return the list of currencies for deposit forms": "Возвращает список валют для форм вкладов",
  "Contact the DepositOne team": "Свяжитесь с командой DepositOne",
  "Create Ticket": "Создать обращение",
  "Theme": "Тема",
  "Category": "Категория",
  "Description": "Описание",
  "Contact Info": "Контактные данные",
  "Send Ticket": "Отправить обращение",
  "Choose category": "Выберите категорию",
  "Choose priority": "Выберите приоритет",
  "Technical issue": "Техническая проблема",
  "Payment": "Оплата",
  "Account": "Аккаунт",
  "Other": "Другое",
  "Low": "Низкий",
  "Medium": "Средний",
  "High": "Высокий",
  "Urgent": "Срочный",
  "Enter theme": "Введите тему",
  "Please describe your problem in detail": "Опишите вашу проблему подробно",
  "Account Id": "Номер аккаунта",
  "Nickname": "Никнейм",
  "Created": "Создан",
  "Last Visit": "Последний вход",
  "Portfolio": "Портфель",
  "Depositors": "Вкладчики",
  "Active Deposits": "Активные вклады",
  "Total Amount": "Общая сумма",
  "Operations": "Операции",
  "Signed Contracts": "Подписанные договоры",
  "Pending Contracts": "Договоры в ожидании",
  "JWT Access Token": "JWT токен доступа",
  "The token is used to access protected endpoints and integrate with the API.": "Токен используется для доступа к защищённым эндпоинтам и интеграции с API.",
  "Release Token": "Выпустить токен",
  "Copy": "Копировать",
  'Click the "Release Token" button to get your JWT, and click the "Copy" button to copy the generated JWT token.': "Нажмите кнопку «Выпустить токен», чтобы получить JWT, и кнопку «Копировать», чтобы скопировать полученный JWT токен.",
  "ID:": "ИДЕНТИФИКАТОР:",
  "DOB:": "ДАТА РОЖДЕНИЯ:",
  "COUNTRY:": "СТРАНА:",
  "EMAIL:": "ПОЧТА:",
  "ADDRESS:": "АДРЕС:",
  "AMOUNT:": "СУММА:",
  "CURRENCY:": "ВАЛЮТА:",
  "INTEREST RATE:": "ПРОЦЕНТНАЯ СТАВКА:",
  "DEADLINE:": "СРОК:",
  "DEPOSITOR:": "ВКЛАДЧИК:",
  "DATE:": "ДАТА:",
  "DEPOSIT ID:": "ID ВКЛАДА:",
  "PAYOUT DATE:": "ДАТА ВЫПЛАТЫ:",
  "TOTAL REFUND:": "ИТОГО К ВОЗВРАТУ:",
  "TOTAL AMOUNT:": "ОБЩАЯ СУММА:",
  "TOTAL INCOME:": "ОБЩИЙ ДОХОД:",
  "January": "Январь",
  "February": "Февраль",
  "March": "Март",
  "April": "Апрель",
  "May": "Май",
  "June": "Июнь",
  "July": "Июль",
  "August": "Август",
  "September": "Сентябрь",
  "October": "Октябрь",
  "November": "Ноябрь",
  "December": "Декабрь",
  "Error": "Ошибка",
  "DepositOne Profile": "DepositOne Профиль",
  "DepositOne Dashboard": "DepositOne Панель",
  "DepositOne Depositors": "DepositOne Вкладчики",
  "DepositOne Depositor Card": "DepositOne Карточка вкладчика",
  "DepositOne New Depositor": "DepositOne Новый вкладчик",
  "DepositOne Deposits": "DepositOne Вклады",
  "DepositOne Deposit Card": "DepositOne Карточка вклада",
  "DepositOne New Deposit": "DepositOne Новый вклад",
  "DepositOne Contracts": "DepositOne Договоры",
  "DepositOne Contract Card": "DepositOne Карточка договора",
  "DepositOne New Contract": "DepositOne Новый договор",
  "DepositOne Reports": "DepositOne Отчёты",
  "DepositOne Return Plans": "DepositOne Планы возврата",
  "DepositOne Return Plan": "DepositOne План возврата",
  "DepositOne Support": "DepositOne Поддержка",
  "DepositOne Login": "DepositOne Вход",
  "DepositOne Registration": "DepositOne Регистрация",
  "DepositOne Reset Password": "DepositOne Сброс пароля",
  "DepositOne Set New Password": "DepositOne Новый пароль",
  "DepositOne Error": "DepositOne Ошибка",
  "Newest": "Сначала новые",
  "All statuses": "Все статусы",
  "Service Unavailable": "Сервис недоступен",
  "Bogdan Vitriak": "Богдан Витряк",
  "OKBI-204B": "ОКБИ-204б",
  "All methods": "Все методы",
  "Internal platform for the operational tracking of deposit agreements and the viewing of analytics.": "Внутренняя платформа для оперативного учёта депозитных договоров и просмотра аналитики.",
  "DepositOne keeps depositor cards, deposits and contracts in one place. Every deposit belongs to a depositor, every contract wraps a single deposit, and the repayment plan is derived from the deposit terms. The platform shows portfolio structure, cash flow by period and the schedule of upcoming returns.": "DepositOne хранит карточки вкладчиков, вклады и договоры в одном месте. Каждый вклад принадлежит вкладчику, каждый договор оборачивает один вклад, а план возврата выводится из условий вклада. Платформа показывает структуру портфеля, денежные потоки по периодам и график предстоящих возвратов.",
  "Core service": "Сервис Core",
  "Supporting service": "Сервис Supporting",
  "Database": "База данных",
  "Authentication": "Авторизация",
  "Data access": "Доступ к данным",
  "SQL without ORM": "SQL без ORM",
  "Registration and sign in protected by JWT": "Регистрация и вход под защитой JWT",
  "Depositor, deposit and contract cards with full create, read, update and delete": "Карточки вкладчиков, вкладов и договоров с полным набором операций: создание, чтение, изменение и удаление",
  "Search, sorting and paging performed by the database": "Поиск, сортировка и постраничный вывод выполняются базой данных",
  "Portfolio analytics with charts and cash flow reports": "Аналитика портфеля с диаграммами и отчётами по денежным потокам",
  "Repayment schedule derived from deposit terms": "График возврата выводится из условий вклада",
  "Fallback answers when a service is unavailable": "Резервные ответы, когда сервис недоступен",
  "Moscow Technology Institute": "Московский технологический институт",
  "Signed": "Подписан",
  "Rejected": "Отклонён",
  "Payout date": "Дата выплаты",
  "Total amount": "Общая сумма",
  "Total income": "Общий доход",
  "About": "О проекте",
  "DepositOne About": "DepositOne О проекте",
  "What the platform does": "Что делает платформа",
  "Features": "Возможности",
  "Technology": "Технологии",
  "Project": "Проект",
  "Author": "Автор",
  "Group": "Группа",
  "Organization": "Организация",
  "Version": "Версия",
  "License": "Лицензия",
};

const PATTERNS = [
  [/^(\d+) records found$/, "Найдено записей: $1"],
  [/^N\/A records found$/, "Записи не найдены"],
  [/^Page (\d+) of (\d+)$/, "Страница $1 из $2"],
  [/^Error (\d+)$/, "Ошибка $1"],
  [/^Please fill in the (.+) field$/, "Заполните поле $1"],
  [/^(\d+) DEPOSITS$/, "$1 ВКЛАДОВ"],
  [/^(\d+)D$/, "$1 ДН"],
  [/^([\d.]+)% AI$/, "$1% ГОДОВЫХ"],
  [/^1 month$/, "1 месяц"],
  [/^(\d+) months$/, "$1 мес."],
  [/^1 day$/, "1 день"],
  [/^(\d+) days$/, "$1 дн."],
];

function currentLanguage() {
  return localStorage.getItem("language") || ENGLISH;
}

function translateWord(word) {
  const translation = TRANSLATIONS[word];
  if (typeof translation === "string") {
    return translation;
  }
  return word;
}

function translatePattern(key) {
  for (const pattern of PATTERNS) {
    const found = key.match(pattern[0]);
    if (!found) {
      continue;
    }
    let result = pattern[1];
    for (let index = 1; index < found.length; index = index + 1) {
      result = result.replace("$" + index, translateWord(found[index]));
    }
    return result;
  }
  return null;
}

function translateText(text) {
  const key = text.trim();
  if (!key) {
    return text;
  }
  const translation = TRANSLATIONS[key];
  if (typeof translation === "string") {
    return text.replace(key, translation);
  }
  const pattern = translatePattern(key);
  if (pattern) {
    return text.replace(key, pattern);
  }
  return text;
}

function translateNode(node) {
  if (node.nodeType === Node.TEXT_NODE) {
    node.nodeValue = translateText(node.nodeValue);
    return;
  }
  if (node.placeholder) {
    node.placeholder = translateText(node.placeholder);
  }
  node.childNodes.forEach(translateNode);
}

function translatePage() {
  document.title = translateText(document.title);
  translateNode(document.body);
}

if (currentLanguage() === RUSSIAN) {
  document.documentElement.lang = "ru";
  translatePage();
  new MutationObserver(translatePage).observe(document.body, { childList: true, subtree: true });
}
