def get_apis():
    return {
        "apis": [
            {
                "name": "Register",
                "type": "POST",
                "path": "/api/register",
                "description": "Create a new user account",
                "auth": "None",
                "module": "Auth",
                "service": "Supporting",
            },
            {
                "name": "Login",
                "type": "POST",
                "path": "/api/login",
                "description": "Sign in and receive an access token",
                "auth": "None",
                "module": "Auth",
                "service": "Supporting",
            },
            {
                "name": "Reset Check",
                "type": "POST",
                "path": "/api/reset-password/check",
                "description": "Check an account before a password reset",
                "auth": "None",
                "module": "Auth",
                "service": "Supporting",
            },
            {
                "name": "Reset Confirm",
                "type": "POST",
                "path": "/api/reset-password/confirm",
                "description": "Save a new password for an account",
                "auth": "None",
                "module": "Auth",
                "service": "Supporting",
            },
            {
                "name": "Dashboard",
                "type": "GET",
                "path": "/api/dashboard",
                "description": "Return dashboard analytics data",
                "auth": "JWT",
                "module": "Dashboard",
                "service": "Supporting",
            },
            {
                "name": "Api List",
                "type": "GET",
                "path": "/api/apis",
                "description": "Return the list of available endpoints",
                "auth": "JWT",
                "module": "System",
                "service": "Supporting",
            },
            {
                "name": "Profile",
                "type": "GET",
                "path": "/api/profile",
                "description": "Return the account card of the current user",
                "auth": "JWT",
                "module": "Profile",
                "service": "Supporting",
            },
            {
                "name": "Profile Token",
                "type": "POST",
                "path": "/api/profile/token",
                "description": "Release a new access token for the current user",
                "auth": "JWT",
                "module": "Profile",
                "service": "Supporting",
            },
            {
                "name": "Depositor List",
                "type": "GET",
                "path": "/api/depositors",
                "description": "Search, sort and page through depositors",
                "auth": "JWT",
                "module": "Depositors",
                "service": "Core",
            },
            {
                "name": "Depositor Create",
                "type": "POST",
                "path": "/api/depositors",
                "description": "Create a depositor card",
                "auth": "JWT",
                "module": "Depositors",
                "service": "Core",
            },
            {
                "name": "Depositor Options",
                "type": "GET",
                "path": "/api/depositors/options",
                "description": "Return depositors for select fields",
                "auth": "JWT",
                "module": "Depositors",
                "service": "Core",
            },
            {
                "name": "Depositor Card",
                "type": "GET",
                "path": "/api/depositors/{depositor_id}",
                "description": "Return one depositor card",
                "auth": "JWT",
                "module": "Depositors",
                "service": "Core",
            },
            {
                "name": "Depositor Update",
                "type": "PUT",
                "path": "/api/depositors/{depositor_id}",
                "description": "Update a depositor card",
                "auth": "JWT",
                "module": "Depositors",
                "service": "Core",
            },
            {
                "name": "Depositor Delete",
                "type": "DELETE",
                "path": "/api/depositors/{depositor_id}",
                "description": "Delete a depositor without active deposits",
                "auth": "JWT",
                "module": "Depositors",
                "service": "Core",
            },
            {
                "name": "Deposit List",
                "type": "GET",
                "path": "/api/deposits",
                "description": "Search, sort and page through deposits",
                "auth": "JWT",
                "module": "Deposits",
                "service": "Core",
            },
            {
                "name": "Deposit Create",
                "type": "POST",
                "path": "/api/deposits",
                "description": "Open a new deposit for a depositor",
                "auth": "JWT",
                "module": "Deposits",
                "service": "Core",
            },
            {
                "name": "Deposit Options",
                "type": "GET",
                "path": "/api/deposits/options",
                "description": "Return deposits for contract forms",
                "auth": "JWT",
                "module": "Deposits",
                "service": "Core",
            },
            {
                "name": "Deposit Stats",
                "type": "GET",
                "path": "/api/deposits/stats",
                "description": "Return deposit counts and amounts by status and currency",
                "auth": "JWT",
                "module": "Deposits",
                "service": "Core",
            },
            {
                "name": "Deposit Card",
                "type": "GET",
                "path": "/api/deposits/{deposit_id}",
                "description": "Return one deposit with the calculated term",
                "auth": "JWT",
                "module": "Deposits",
                "service": "Core",
            },
            {
                "name": "Deposit Update",
                "type": "PUT",
                "path": "/api/deposits/{deposit_id}",
                "description": "Update the parameters of a deposit",
                "auth": "JWT",
                "module": "Deposits",
                "service": "Core",
            },
            {
                "name": "Deposit Delete",
                "type": "DELETE",
                "path": "/api/deposits/{deposit_id}",
                "description": "Delete a deposit without a contract",
                "auth": "JWT",
                "module": "Deposits",
                "service": "Core",
            },
            {
                "name": "Contract List",
                "type": "GET",
                "path": "/api/contracts",
                "description": "Search, sort and page through contracts",
                "auth": "JWT",
                "module": "Contracts",
                "service": "Core",
            },
            {
                "name": "Contract Create",
                "type": "POST",
                "path": "/api/contracts",
                "description": "Create a contract for a deposit",
                "auth": "JWT",
                "module": "Contracts",
                "service": "Core",
            },
            {
                "name": "Contract Card",
                "type": "GET",
                "path": "/api/contracts/{contract_id}",
                "description": "Return one contract with deposit data",
                "auth": "JWT",
                "module": "Contracts",
                "service": "Core",
            },
            {
                "name": "Contract Update",
                "type": "PUT",
                "path": "/api/contracts/{contract_id}",
                "description": "Update the terms of a contract",
                "auth": "JWT",
                "module": "Contracts",
                "service": "Core",
            },
            {
                "name": "Contract Delete",
                "type": "DELETE",
                "path": "/api/contracts/{contract_id}",
                "description": "Delete a contract",
                "auth": "JWT",
                "module": "Contracts",
                "service": "Core",
            },
            {
                "name": "Report List",
                "type": "GET",
                "path": "/api/reports",
                "description": "Return portfolio reports by depositor",
                "auth": "JWT",
                "module": "Reports",
                "service": "Core",
            },
            {
                "name": "Cash Flow",
                "type": "GET",
                "path": "/api/reports/cash-flow",
                "description": "Return inflow, outflow and net liquidity by period",
                "auth": "JWT",
                "module": "Reports",
                "service": "Core",
            },
            {
                "name": "Plan List",
                "type": "GET",
                "path": "/api/plans",
                "description": "Search and page through return plans",
                "auth": "JWT",
                "module": "Plans",
                "service": "Core",
            },
            {
                "name": "Plan Summary",
                "type": "GET",
                "path": "/api/plans/summary",
                "description": "Return monthly results and the priority list",
                "auth": "JWT",
                "module": "Plans",
                "service": "Core",
            },
            {
                "name": "Plan Card",
                "type": "GET",
                "path": "/api/plans/{deposit_id}",
                "description": "Return the repayment plan of one deposit",
                "auth": "JWT",
                "module": "Plans",
                "service": "Core",
            },
            {
                "name": "Portfolio",
                "type": "GET",
                "path": "/api/portfolio",
                "description": "Return portfolio and contract totals",
                "auth": "JWT",
                "module": "Portfolio",
                "service": "Core",
            },
            {
                "name": "Country List",
                "type": "GET",
                "path": "/api/countries",
                "description": "Return the list of countries for depositor forms",
                "auth": "JWT",
                "module": "Dictionaries",
                "service": "Core",
            },
            {
                "name": "Currency List",
                "type": "GET",
                "path": "/api/currencies",
                "description": "Return the list of currencies for deposit forms",
                "auth": "JWT",
                "module": "Dictionaries",
                "service": "Core",
            },
        ]
    }
